# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170629_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='label',
            field=models.ManyToManyField(to='posts.PostLabel'),
        ),
    ]
