# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20170629_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentcomment',
            name='is_deleted',
            field=models.SmallIntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_deleted',
            field=models.SmallIntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='is_deleted',
            field=models.SmallIntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0),
        ),
        migrations.AlterField(
            model_name='postimages',
            name='is_deleted',
            field=models.SmallIntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0),
        ),
        migrations.AlterField(
            model_name='postvideos',
            name='is_deleted',
            field=models.SmallIntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0),
        ),
    ]
